package com.pets.selenium.tests;

// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;


public class BaseTests {
    ChromeDriver chromeDriver = new ChromeDriver();



@Test
    public void openBrowser() {
        chromeDriver.get("http://localhost:3000");
    assertThat(chromeDriver.getTitle(), is("React App"));
    }
}
